### ISSUE TITLE
Release of doxyrest_b with the latest doxyrest (2.1.2)

### ISSUE THREAD

**Issue by igorsafo** [vovkos/doxyrest_b#1]
Hi @vovkos and @Voxiferus ,
Is it possible to make a release with the latest version of Doxyrest (2.1.2)?
This will allow to get the Doxyrest compatible with the latest Sphinx available in conda-forge.
I created a [PR](https://github.com/conda-forge/doxyrest-feedstock/pull/2) for doxyrest-feedstock, but I wasn't aware that doxyrest-feedstock relies on doxyrest-b and not on doxyrest, so I got an error.

Regards,
Igor Safonov

**Comment by igorsafo** [comment]
Just to clarify I request a new release so conda-forge can access it using `https://github.com/vovkos/doxyrest_b/releases/download/doxyrest-2.1.2/doxyrest-2.1.2-src.tar.xz`. The problem is that packages in conda-forge are immutable, so even doxyrest_b is updated to work with the latest doxyrest using submodule, it will not be visible for conda-forge, because it points to a particular hash used when version 2.0.0 was released. Releasing new version of doxyrest_b will resolve the issue.

Regards,
Igor Safonov

**Comment by vovkos** [comment]
Understood. Took me a while to fix a broken expat link; decided to stick with the original version and replaced the download link. The source bundle release version 2.1.2 is ready.

**Comment by igorsafo** [comment]
Thank you! Conda-forge automatically created a [PR](https://github.com/conda-forge/doxyrest-feedstock/pull/3) with new release.
